@include('back.admins.modal.create')
@include('back.users.modal.create')
@include('back.settings.modal.settings')
@include('back.frontends.modal.frontends')
@include('back.countreis.modal.create')
@include('back.products.modal.create')
@include('back.sliders.modal.create')
@include('back.about.modal.create')
@include('back.ads.modal.create')
@include('back.news.modal.create')
@include('back.testimonial.modal.create')

